### ISSUE TITLE
Deprecated configuration, SEO suggestion and math support

### ISSUE THREAD

**Issue by maristie** [NCSU-Libraries/jekyll-academic#3]
### Deprecated configuration
The latest Jekyll has deprecated `gems` ([_config.yml](https://github.com/NCSU-Libraries/jekyll-academic/blob/master/_config.yml), line 57). Could you please rename it to `plugins`?

### SEO suggestion
In addition, is it possible to use `jekyll-seo-tag` in `_config.yml` and add `{% seo %}` in template files to optimize website? According to the [official article](https://help.github.com/articles/search-engine-optimization-for-github-pages/), 
> To tell the plugin where to put your meta tag information, you must add the SEO tag right before `head` in your site template files. For example, in `_layouts/_default.html`:
```
<html>
  <head>
    {% include head.html %}
    {% seo %}
  </head>
</html>
```

### Math support
According to [MathJax Documentation](https://docs.mathjax.org/en/latest/start.html), could you please add MathJax support in [_includes/_head.html](https://github.com/NCSU-Libraries/jekyll-academic/blob/master/_includes/_head.html) or [_includes/_scripts.html](https://github.com/NCSU-Libraries/jekyll-academic/blob/master/_includes/_scripts.html)? (`<head>` block is preferred, though)

Or a faster math render KaTeX using the default math engine provided by Kramdown: https://kramdown.gettalong.org/math_engine/mathjax.html

Thanks!

**Comment by toddstoffer** [comment]
Hi @Maristie Thanks for the suggestions! I have updated the config file and added jekyll-seo-tags to the project. I am going to close this issue and open a new one for adding Math support. I would like to look into math support a little more before adding it to the project. Thanks!
