### ISSUE TITLE
Attach reveal.js directory as submodule

### ISSUE THREAD

**Issue by maristie** [NCSU-Libraries/jekyll-academic#5]
Is it possible to add [reveal.js](https://github.com/hakimel/reveal.js) as a submodule? In this way users can get the latest version conveniently, and it's more structured.

Code:
```sh
# run in the root directory of the repo
$ git submodule add https://github.com/hakimel/reveal.js.git
```

**Comment by jcraitz** [comment]
Great idea!  And we've finally merged it, see #29.  Thank you!
